import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry";
import Box from "@mui/material/Box";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import QueryProvider from "@/components/QueryProvider";
import { LocaleProvider } from "@/context/LocaleContext"
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <LocaleProvider>
          <QueryProvider>
            <ThemeRegistry>
              <Box sx={{ display: 'flex', flexDirection: "column", width: '100vw', height: '100vh' }}>
                <Header title={"your cool todo list"} todoCount={0} />

                <Box sx={{ display: 'flex', flexDirection: "column", justifyContent: 'center', width: '100%', overflowY: "scroll", flex: 1 }}>
                  {children}
                </Box>

                <Footer author={"me"} />
              </Box>
            </ThemeRegistry>
          </QueryProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
