import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/components/providers/ThemeRegistry";
import Box from "@mui/material/Box";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import QueryProvider from "@/components/providers/QueryProvider";
import { LocaleProvider } from "@/context/LocaleContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
            <body>
                <LocaleProvider>
                    <QueryProvider>
                        <ThemeRegistry>
                            <Box
                                sx={{
                                    display: "flex",
                                    flexDirection: "column",
                                    width: "100vw",
                                    height: "100vh",
                                }}
                            >
                                <Header />

                                <Box
                                    sx={{
                                        display: "flex",
                                        flexDirection: "column",
                                        width: "100%",
                                        overflowY: "auto",
                                        scrollbarGutter: "stable",
                                        flex: 1,
                                    }}
                                >
                                    {children}
                                </Box>

                                <Footer />
                            </Box>
                        </ThemeRegistry>
                    </QueryProvider>
                </LocaleProvider>
            </body>
        </html>
    );
}
